Production deployments from CI
osuAkatsuki/hanayo pull request #83
Opened 2023-10-10 06:43 UTC by cmyui

2023-10-11 07:34 UTC, tsunyoku requested changes

2023-10-11 07:34 UTC, tsunyoku commented on scripts/start.sh
> +  akatsuki vault get bancho-service $APP_ENV -o .env
```suggestion
  akatsuki vault get hanayo $APP_ENV -o .env
```

2023-10-11 23:23 UTC, cmyui commented on scripts/start.sh
> +  akatsuki vault get bancho-service $APP_ENV -o .env
lol

2023-10-22 16:31 UTC, cmyui commented on .github/workflows/production-deploy.yml
> +              hanayo
```suggestion
              hanayo-api
```

2023-10-22 16:32 UTC, cmyui commented on scripts/start.sh
> +  pip install -i $PYPI_INDEX_URL akatsuki-cli
```suggestion
  # TODO: is there a better way to deal with this?
  pip install --break-system-packages -i $PYPI_INDEX_URL akatsuki-cli
```

2023-10-22 16:34 UTC, cmyui commented on .github/workflows/production-deploy.yml
> +      - main
```suggestion
      - master
```

2023-10-22 16:36 UTC, merged